import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const vaultPath = process.env.OBSIDIAN_VAULT_PATH;

// Sync files to vault after build
function syncToVault() {
	if (!vaultPath) {
		return; // Silently skip if no vault path is set
	}

	const pluginDir = join(vaultPath, '.obsidian', 'plugins', 'search-shortlist');
	const filesToCopy = [
		{ src: 'main.js', dest: 'main.js' },
		{ src: 'manifest.json', dest: 'manifest.json' },
		{ src: 'styles.css', dest: 'styles.css' },
	];

	// Ensure plugin directory exists
	if (!existsSync(pluginDir)) {
		mkdirSync(pluginDir, { recursive: true });
	}

	// Copy files
	let copied = 0;
	for (const file of filesToCopy) {
		const srcPath = join(__dirname, file.src);
		const destPath = join(pluginDir, file.dest);
		
		if (!existsSync(srcPath)) {
			continue;
		}
		
		try {
			copyFileSync(srcPath, destPath);
			copied++;
		} catch (error) {
			console.error(`❌ Error copying ${file.src}:`, error.message);
		}
	}

	if (copied > 0) {
		console.log(`✨ Synced ${copied} file(s) to vault (${vaultPath})`);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
